// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: multi_team_communication.proto

#ifndef PROTOBUF_multi_5fteam_5fcommunication_2eproto__INCLUDED
#define PROTOBUF_multi_5fteam_5fcommunication_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace multi_team_comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_multi_5fteam_5fcommunication_2eproto();
void protobuf_AssignDesc_multi_5fteam_5fcommunication_2eproto();
void protobuf_ShutdownFile_multi_5fteam_5fcommunication_2eproto();

class TeamPlan;
class RobotPlan;
class Location;
class Pose;

enum RobotPlan_RobotRole {
  RobotPlan_RobotRole_Default = 0,
  RobotPlan_RobotRole_Goalie = 1,
  RobotPlan_RobotRole_Defense = 2,
  RobotPlan_RobotRole_Offense = 3
};
bool RobotPlan_RobotRole_IsValid(int value);
const RobotPlan_RobotRole RobotPlan_RobotRole_RobotRole_MIN = RobotPlan_RobotRole_Default;
const RobotPlan_RobotRole RobotPlan_RobotRole_RobotRole_MAX = RobotPlan_RobotRole_Offense;
const int RobotPlan_RobotRole_RobotRole_ARRAYSIZE = RobotPlan_RobotRole_RobotRole_MAX + 1;

const ::google::protobuf::EnumDescriptor* RobotPlan_RobotRole_descriptor();
inline const ::std::string& RobotPlan_RobotRole_Name(RobotPlan_RobotRole value) {
  return ::google::protobuf::internal::NameOfEnum(
    RobotPlan_RobotRole_descriptor(), value);
}
inline bool RobotPlan_RobotRole_Parse(
    const ::std::string& name, RobotPlan_RobotRole* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RobotPlan_RobotRole>(
    RobotPlan_RobotRole_descriptor(), name, value);
}
// ===================================================================

class TeamPlan : public ::google::protobuf::Message {
 public:
  TeamPlan();
  virtual ~TeamPlan();

  TeamPlan(const TeamPlan& from);

  inline TeamPlan& operator=(const TeamPlan& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TeamPlan& default_instance();

  void Swap(TeamPlan* other);

  // implements Message ----------------------------------------------

  TeamPlan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TeamPlan& from);
  void MergeFrom(const TeamPlan& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .multi_team_comm.RobotPlan plans = 1;
  inline int plans_size() const;
  inline void clear_plans();
  static const int kPlansFieldNumber = 1;
  inline const ::multi_team_comm::RobotPlan& plans(int index) const;
  inline ::multi_team_comm::RobotPlan* mutable_plans(int index);
  inline ::multi_team_comm::RobotPlan* add_plans();
  inline const ::google::protobuf::RepeatedPtrField< ::multi_team_comm::RobotPlan >&
      plans() const;
  inline ::google::protobuf::RepeatedPtrField< ::multi_team_comm::RobotPlan >*
      mutable_plans();

  // @@protoc_insertion_point(class_scope:multi_team_comm.TeamPlan)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::multi_team_comm::RobotPlan > plans_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_AssignDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_ShutdownFile_multi_5fteam_5fcommunication_2eproto();

  void InitAsDefaultInstance();
  static TeamPlan* default_instance_;
};
// -------------------------------------------------------------------

class RobotPlan : public ::google::protobuf::Message {
 public:
  RobotPlan();
  virtual ~RobotPlan();

  RobotPlan(const RobotPlan& from);

  inline RobotPlan& operator=(const RobotPlan& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RobotPlan& default_instance();

  void Swap(RobotPlan* other);

  // implements Message ----------------------------------------------

  RobotPlan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RobotPlan& from);
  void MergeFrom(const RobotPlan& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RobotPlan_RobotRole RobotRole;
  static const RobotRole Default = RobotPlan_RobotRole_Default;
  static const RobotRole Goalie = RobotPlan_RobotRole_Goalie;
  static const RobotRole Defense = RobotPlan_RobotRole_Defense;
  static const RobotRole Offense = RobotPlan_RobotRole_Offense;
  static inline bool RobotRole_IsValid(int value) {
    return RobotPlan_RobotRole_IsValid(value);
  }
  static const RobotRole RobotRole_MIN =
    RobotPlan_RobotRole_RobotRole_MIN;
  static const RobotRole RobotRole_MAX =
    RobotPlan_RobotRole_RobotRole_MAX;
  static const int RobotRole_ARRAYSIZE =
    RobotPlan_RobotRole_RobotRole_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RobotRole_descriptor() {
    return RobotPlan_RobotRole_descriptor();
  }
  static inline const ::std::string& RobotRole_Name(RobotRole value) {
    return RobotPlan_RobotRole_Name(value);
  }
  static inline bool RobotRole_Parse(const ::std::string& name,
      RobotRole* value) {
    return RobotPlan_RobotRole_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint32 robot_id = 1;
  inline bool has_robot_id() const;
  inline void clear_robot_id();
  static const int kRobotIdFieldNumber = 1;
  inline ::google::protobuf::uint32 robot_id() const;
  inline void set_robot_id(::google::protobuf::uint32 value);

  // optional .multi_team_comm.RobotPlan.RobotRole role = 2;
  inline bool has_role() const;
  inline void clear_role();
  static const int kRoleFieldNumber = 2;
  inline ::multi_team_comm::RobotPlan_RobotRole role() const;
  inline void set_role(::multi_team_comm::RobotPlan_RobotRole value);

  // optional .multi_team_comm.Pose nav_target = 3;
  inline bool has_nav_target() const;
  inline void clear_nav_target();
  static const int kNavTargetFieldNumber = 3;
  inline const ::multi_team_comm::Pose& nav_target() const;
  inline ::multi_team_comm::Pose* mutable_nav_target();
  inline ::multi_team_comm::Pose* release_nav_target();
  inline void set_allocated_nav_target(::multi_team_comm::Pose* nav_target);

  // optional .multi_team_comm.Location shot_target = 4;
  inline bool has_shot_target() const;
  inline void clear_shot_target();
  static const int kShotTargetFieldNumber = 4;
  inline const ::multi_team_comm::Location& shot_target() const;
  inline ::multi_team_comm::Location* mutable_shot_target();
  inline ::multi_team_comm::Location* release_shot_target();
  inline void set_allocated_shot_target(::multi_team_comm::Location* shot_target);

  // @@protoc_insertion_point(class_scope:multi_team_comm.RobotPlan)
 private:
  inline void set_has_robot_id();
  inline void clear_has_robot_id();
  inline void set_has_role();
  inline void clear_has_role();
  inline void set_has_nav_target();
  inline void clear_has_nav_target();
  inline void set_has_shot_target();
  inline void clear_has_shot_target();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 robot_id_;
  int role_;
  ::multi_team_comm::Pose* nav_target_;
  ::multi_team_comm::Location* shot_target_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_AssignDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_ShutdownFile_multi_5fteam_5fcommunication_2eproto();

  void InitAsDefaultInstance();
  static RobotPlan* default_instance_;
};
// -------------------------------------------------------------------

class Location : public ::google::protobuf::Message {
 public:
  Location();
  virtual ~Location();

  Location(const Location& from);

  inline Location& operator=(const Location& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Location& default_instance();

  void Swap(Location* other);

  // implements Message ----------------------------------------------

  Location* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Location& from);
  void MergeFrom(const Location& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:multi_team_comm.Location)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_AssignDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_ShutdownFile_multi_5fteam_5fcommunication_2eproto();

  void InitAsDefaultInstance();
  static Location* default_instance_;
};
// -------------------------------------------------------------------

class Pose : public ::google::protobuf::Message {
 public:
  Pose();
  virtual ~Pose();

  Pose(const Pose& from);

  inline Pose& operator=(const Pose& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pose& default_instance();

  void Swap(Pose* other);

  // implements Message ----------------------------------------------

  Pose* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pose& from);
  void MergeFrom(const Pose& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .multi_team_comm.Location loc = 1;
  inline bool has_loc() const;
  inline void clear_loc();
  static const int kLocFieldNumber = 1;
  inline const ::multi_team_comm::Location& loc() const;
  inline ::multi_team_comm::Location* mutable_loc();
  inline ::multi_team_comm::Location* release_loc();
  inline void set_allocated_loc(::multi_team_comm::Location* loc);

  // optional float heading = 2;
  inline bool has_heading() const;
  inline void clear_heading();
  static const int kHeadingFieldNumber = 2;
  inline float heading() const;
  inline void set_heading(float value);

  // @@protoc_insertion_point(class_scope:multi_team_comm.Pose)
 private:
  inline void set_has_loc();
  inline void clear_has_loc();
  inline void set_has_heading();
  inline void clear_has_heading();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::multi_team_comm::Location* loc_;
  float heading_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_AssignDesc_multi_5fteam_5fcommunication_2eproto();
  friend void protobuf_ShutdownFile_multi_5fteam_5fcommunication_2eproto();

  void InitAsDefaultInstance();
  static Pose* default_instance_;
};
// ===================================================================


// ===================================================================

// TeamPlan

// repeated .multi_team_comm.RobotPlan plans = 1;
inline int TeamPlan::plans_size() const {
  return plans_.size();
}
inline void TeamPlan::clear_plans() {
  plans_.Clear();
}
inline const ::multi_team_comm::RobotPlan& TeamPlan::plans(int index) const {
  return plans_.Get(index);
}
inline ::multi_team_comm::RobotPlan* TeamPlan::mutable_plans(int index) {
  return plans_.Mutable(index);
}
inline ::multi_team_comm::RobotPlan* TeamPlan::add_plans() {
  return plans_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::multi_team_comm::RobotPlan >&
TeamPlan::plans() const {
  return plans_;
}
inline ::google::protobuf::RepeatedPtrField< ::multi_team_comm::RobotPlan >*
TeamPlan::mutable_plans() {
  return &plans_;
}

// -------------------------------------------------------------------

// RobotPlan

// required uint32 robot_id = 1;
inline bool RobotPlan::has_robot_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RobotPlan::set_has_robot_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RobotPlan::clear_has_robot_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RobotPlan::clear_robot_id() {
  robot_id_ = 0u;
  clear_has_robot_id();
}
inline ::google::protobuf::uint32 RobotPlan::robot_id() const {
  return robot_id_;
}
inline void RobotPlan::set_robot_id(::google::protobuf::uint32 value) {
  set_has_robot_id();
  robot_id_ = value;
}

// optional .multi_team_comm.RobotPlan.RobotRole role = 2;
inline bool RobotPlan::has_role() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RobotPlan::set_has_role() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RobotPlan::clear_has_role() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RobotPlan::clear_role() {
  role_ = 0;
  clear_has_role();
}
inline ::multi_team_comm::RobotPlan_RobotRole RobotPlan::role() const {
  return static_cast< ::multi_team_comm::RobotPlan_RobotRole >(role_);
}
inline void RobotPlan::set_role(::multi_team_comm::RobotPlan_RobotRole value) {
  assert(::multi_team_comm::RobotPlan_RobotRole_IsValid(value));
  set_has_role();
  role_ = value;
}

// optional .multi_team_comm.Pose nav_target = 3;
inline bool RobotPlan::has_nav_target() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RobotPlan::set_has_nav_target() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RobotPlan::clear_has_nav_target() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RobotPlan::clear_nav_target() {
  if (nav_target_ != NULL) nav_target_->::multi_team_comm::Pose::Clear();
  clear_has_nav_target();
}
inline const ::multi_team_comm::Pose& RobotPlan::nav_target() const {
  return nav_target_ != NULL ? *nav_target_ : *default_instance_->nav_target_;
}
inline ::multi_team_comm::Pose* RobotPlan::mutable_nav_target() {
  set_has_nav_target();
  if (nav_target_ == NULL) nav_target_ = new ::multi_team_comm::Pose;
  return nav_target_;
}
inline ::multi_team_comm::Pose* RobotPlan::release_nav_target() {
  clear_has_nav_target();
  ::multi_team_comm::Pose* temp = nav_target_;
  nav_target_ = NULL;
  return temp;
}
inline void RobotPlan::set_allocated_nav_target(::multi_team_comm::Pose* nav_target) {
  delete nav_target_;
  nav_target_ = nav_target;
  if (nav_target) {
    set_has_nav_target();
  } else {
    clear_has_nav_target();
  }
}

// optional .multi_team_comm.Location shot_target = 4;
inline bool RobotPlan::has_shot_target() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RobotPlan::set_has_shot_target() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RobotPlan::clear_has_shot_target() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RobotPlan::clear_shot_target() {
  if (shot_target_ != NULL) shot_target_->::multi_team_comm::Location::Clear();
  clear_has_shot_target();
}
inline const ::multi_team_comm::Location& RobotPlan::shot_target() const {
  return shot_target_ != NULL ? *shot_target_ : *default_instance_->shot_target_;
}
inline ::multi_team_comm::Location* RobotPlan::mutable_shot_target() {
  set_has_shot_target();
  if (shot_target_ == NULL) shot_target_ = new ::multi_team_comm::Location;
  return shot_target_;
}
inline ::multi_team_comm::Location* RobotPlan::release_shot_target() {
  clear_has_shot_target();
  ::multi_team_comm::Location* temp = shot_target_;
  shot_target_ = NULL;
  return temp;
}
inline void RobotPlan::set_allocated_shot_target(::multi_team_comm::Location* shot_target) {
  delete shot_target_;
  shot_target_ = shot_target;
  if (shot_target) {
    set_has_shot_target();
  } else {
    clear_has_shot_target();
  }
}

// -------------------------------------------------------------------

// Location

// required int32 x = 1;
inline bool Location::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Location::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Location::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Location::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Location::x() const {
  return x_;
}
inline void Location::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 y = 2;
inline bool Location::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Location::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Location::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Location::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Location::y() const {
  return y_;
}
inline void Location::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// Pose

// optional .multi_team_comm.Location loc = 1;
inline bool Pose::has_loc() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pose::set_has_loc() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pose::clear_has_loc() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pose::clear_loc() {
  if (loc_ != NULL) loc_->::multi_team_comm::Location::Clear();
  clear_has_loc();
}
inline const ::multi_team_comm::Location& Pose::loc() const {
  return loc_ != NULL ? *loc_ : *default_instance_->loc_;
}
inline ::multi_team_comm::Location* Pose::mutable_loc() {
  set_has_loc();
  if (loc_ == NULL) loc_ = new ::multi_team_comm::Location;
  return loc_;
}
inline ::multi_team_comm::Location* Pose::release_loc() {
  clear_has_loc();
  ::multi_team_comm::Location* temp = loc_;
  loc_ = NULL;
  return temp;
}
inline void Pose::set_allocated_loc(::multi_team_comm::Location* loc) {
  delete loc_;
  loc_ = loc;
  if (loc) {
    set_has_loc();
  } else {
    clear_has_loc();
  }
}

// optional float heading = 2;
inline bool Pose::has_heading() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Pose::set_has_heading() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Pose::clear_has_heading() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Pose::clear_heading() {
  heading_ = 0;
  clear_has_heading();
}
inline float Pose::heading() const {
  return heading_;
}
inline void Pose::set_heading(float value) {
  set_has_heading();
  heading_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace multi_team_comm

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::multi_team_comm::RobotPlan_RobotRole>() {
  return ::multi_team_comm::RobotPlan_RobotRole_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_multi_5fteam_5fcommunication_2eproto__INCLUDED
