// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radio_protocol_wrapper.proto

#ifndef PROTOBUF_radio_5fprotocol_5fwrapper_2eproto__INCLUDED
#define PROTOBUF_radio_5fprotocol_5fwrapper_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "radio_protocol_command.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_radio_5fprotocol_5fwrapper_2eproto();
void protobuf_AssignDesc_radio_5fprotocol_5fwrapper_2eproto();
void protobuf_ShutdownFile_radio_5fprotocol_5fwrapper_2eproto();

class RadioProtocolWrapper;

// ===================================================================

class RadioProtocolWrapper : public ::google::protobuf::Message {
 public:
  RadioProtocolWrapper();
  virtual ~RadioProtocolWrapper();
  
  RadioProtocolWrapper(const RadioProtocolWrapper& from);
  
  inline RadioProtocolWrapper& operator=(const RadioProtocolWrapper& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RadioProtocolWrapper& default_instance();
  
  void Swap(RadioProtocolWrapper* other);
  
  // implements Message ----------------------------------------------
  
  RadioProtocolWrapper* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RadioProtocolWrapper& from);
  void MergeFrom(const RadioProtocolWrapper& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .RadioProtocolCommand command = 1;
  inline int command_size() const;
  inline void clear_command();
  static const int kCommandFieldNumber = 1;
  inline const ::RadioProtocolCommand& command(int index) const;
  inline ::RadioProtocolCommand* mutable_command(int index);
  inline ::RadioProtocolCommand* add_command();
  inline const ::google::protobuf::RepeatedPtrField< ::RadioProtocolCommand >&
      command() const;
  inline ::google::protobuf::RepeatedPtrField< ::RadioProtocolCommand >*
      mutable_command();
  
  // @@protoc_insertion_point(class_scope:RadioProtocolWrapper)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::RadioProtocolCommand > command_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_radio_5fprotocol_5fwrapper_2eproto();
  friend void protobuf_AssignDesc_radio_5fprotocol_5fwrapper_2eproto();
  friend void protobuf_ShutdownFile_radio_5fprotocol_5fwrapper_2eproto();
  
  void InitAsDefaultInstance();
  static RadioProtocolWrapper* default_instance_;
};
// ===================================================================


// ===================================================================

// RadioProtocolWrapper

// repeated .RadioProtocolCommand command = 1;
inline int RadioProtocolWrapper::command_size() const {
  return command_.size();
}
inline void RadioProtocolWrapper::clear_command() {
  command_.Clear();
}
inline const ::RadioProtocolCommand& RadioProtocolWrapper::command(int index) const {
  return command_.Get(index);
}
inline ::RadioProtocolCommand* RadioProtocolWrapper::mutable_command(int index) {
  return command_.Mutable(index);
}
inline ::RadioProtocolCommand* RadioProtocolWrapper::add_command() {
  return command_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::RadioProtocolCommand >&
RadioProtocolWrapper::command() const {
  return command_;
}
inline ::google::protobuf::RepeatedPtrField< ::RadioProtocolCommand >*
RadioProtocolWrapper::mutable_command() {
  return &command_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_radio_5fprotocol_5fwrapper_2eproto__INCLUDED
