// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radio_protocol_command.proto

#ifndef PROTOBUF_radio_5fprotocol_5fcommand_2eproto__INCLUDED
#define PROTOBUF_radio_5fprotocol_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_radio_5fprotocol_5fcommand_2eproto();
void protobuf_AssignDesc_radio_5fprotocol_5fcommand_2eproto();
void protobuf_ShutdownFile_radio_5fprotocol_5fcommand_2eproto();

class RadioProtocolCommand;

// ===================================================================

class RadioProtocolCommand : public ::google::protobuf::Message {
 public:
  RadioProtocolCommand();
  virtual ~RadioProtocolCommand();

  RadioProtocolCommand(const RadioProtocolCommand& from);

  inline RadioProtocolCommand& operator=(const RadioProtocolCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadioProtocolCommand& default_instance();

  void Swap(RadioProtocolCommand* other);

  // implements Message ----------------------------------------------

  RadioProtocolCommand* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RadioProtocolCommand& from);
  void MergeFrom(const RadioProtocolCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 robot_id = 1;
  inline bool has_robot_id() const;
  inline void clear_robot_id();
  static const int kRobotIdFieldNumber = 1;
  inline ::google::protobuf::int32 robot_id() const;
  inline void set_robot_id(::google::protobuf::int32 value);

  // required float velocity_x = 2;
  inline bool has_velocity_x() const;
  inline void clear_velocity_x();
  static const int kVelocityXFieldNumber = 2;
  inline float velocity_x() const;
  inline void set_velocity_x(float value);

  // required float velocity_y = 3;
  inline bool has_velocity_y() const;
  inline void clear_velocity_y();
  static const int kVelocityYFieldNumber = 3;
  inline float velocity_y() const;
  inline void set_velocity_y(float value);

  // required float velocity_r = 4;
  inline bool has_velocity_r() const;
  inline void clear_velocity_r();
  static const int kVelocityRFieldNumber = 4;
  inline float velocity_r() const;
  inline void set_velocity_r(float value);

  // optional float flat_kick = 5;
  inline bool has_flat_kick() const;
  inline void clear_flat_kick();
  static const int kFlatKickFieldNumber = 5;
  inline float flat_kick() const;
  inline void set_flat_kick(float value);

  // optional float chip_kick = 6;
  inline bool has_chip_kick() const;
  inline void clear_chip_kick();
  static const int kChipKickFieldNumber = 6;
  inline float chip_kick() const;
  inline void set_chip_kick(float value);

  // optional float dribbler_spin = 7;
  inline bool has_dribbler_spin() const;
  inline void clear_dribbler_spin();
  static const int kDribblerSpinFieldNumber = 7;
  inline float dribbler_spin() const;
  inline void set_dribbler_spin(float value);

  // @@protoc_insertion_point(class_scope:RadioProtocolCommand)
 private:
  inline void set_has_robot_id();
  inline void clear_has_robot_id();
  inline void set_has_velocity_x();
  inline void clear_has_velocity_x();
  inline void set_has_velocity_y();
  inline void clear_has_velocity_y();
  inline void set_has_velocity_r();
  inline void clear_has_velocity_r();
  inline void set_has_flat_kick();
  inline void clear_has_flat_kick();
  inline void set_has_chip_kick();
  inline void clear_has_chip_kick();
  inline void set_has_dribbler_spin();
  inline void clear_has_dribbler_spin();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 robot_id_;
  float velocity_x_;
  float velocity_y_;
  float velocity_r_;
  float flat_kick_;
  float chip_kick_;
  float dribbler_spin_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_radio_5fprotocol_5fcommand_2eproto();
  friend void protobuf_AssignDesc_radio_5fprotocol_5fcommand_2eproto();
  friend void protobuf_ShutdownFile_radio_5fprotocol_5fcommand_2eproto();

  void InitAsDefaultInstance();
  static RadioProtocolCommand* default_instance_;
};
// ===================================================================


// ===================================================================

// RadioProtocolCommand

// required int32 robot_id = 1;
inline bool RadioProtocolCommand::has_robot_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RadioProtocolCommand::set_has_robot_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RadioProtocolCommand::clear_has_robot_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RadioProtocolCommand::clear_robot_id() {
  robot_id_ = 0;
  clear_has_robot_id();
}
inline ::google::protobuf::int32 RadioProtocolCommand::robot_id() const {
  return robot_id_;
}
inline void RadioProtocolCommand::set_robot_id(::google::protobuf::int32 value) {
  set_has_robot_id();
  robot_id_ = value;
}

// required float velocity_x = 2;
inline bool RadioProtocolCommand::has_velocity_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RadioProtocolCommand::set_has_velocity_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RadioProtocolCommand::clear_has_velocity_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RadioProtocolCommand::clear_velocity_x() {
  velocity_x_ = 0;
  clear_has_velocity_x();
}
inline float RadioProtocolCommand::velocity_x() const {
  return velocity_x_;
}
inline void RadioProtocolCommand::set_velocity_x(float value) {
  set_has_velocity_x();
  velocity_x_ = value;
}

// required float velocity_y = 3;
inline bool RadioProtocolCommand::has_velocity_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RadioProtocolCommand::set_has_velocity_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RadioProtocolCommand::clear_has_velocity_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RadioProtocolCommand::clear_velocity_y() {
  velocity_y_ = 0;
  clear_has_velocity_y();
}
inline float RadioProtocolCommand::velocity_y() const {
  return velocity_y_;
}
inline void RadioProtocolCommand::set_velocity_y(float value) {
  set_has_velocity_y();
  velocity_y_ = value;
}

// required float velocity_r = 4;
inline bool RadioProtocolCommand::has_velocity_r() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RadioProtocolCommand::set_has_velocity_r() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RadioProtocolCommand::clear_has_velocity_r() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RadioProtocolCommand::clear_velocity_r() {
  velocity_r_ = 0;
  clear_has_velocity_r();
}
inline float RadioProtocolCommand::velocity_r() const {
  return velocity_r_;
}
inline void RadioProtocolCommand::set_velocity_r(float value) {
  set_has_velocity_r();
  velocity_r_ = value;
}

// optional float flat_kick = 5;
inline bool RadioProtocolCommand::has_flat_kick() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RadioProtocolCommand::set_has_flat_kick() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RadioProtocolCommand::clear_has_flat_kick() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RadioProtocolCommand::clear_flat_kick() {
  flat_kick_ = 0;
  clear_has_flat_kick();
}
inline float RadioProtocolCommand::flat_kick() const {
  return flat_kick_;
}
inline void RadioProtocolCommand::set_flat_kick(float value) {
  set_has_flat_kick();
  flat_kick_ = value;
}

// optional float chip_kick = 6;
inline bool RadioProtocolCommand::has_chip_kick() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RadioProtocolCommand::set_has_chip_kick() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RadioProtocolCommand::clear_has_chip_kick() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RadioProtocolCommand::clear_chip_kick() {
  chip_kick_ = 0;
  clear_has_chip_kick();
}
inline float RadioProtocolCommand::chip_kick() const {
  return chip_kick_;
}
inline void RadioProtocolCommand::set_chip_kick(float value) {
  set_has_chip_kick();
  chip_kick_ = value;
}

// optional float dribbler_spin = 7;
inline bool RadioProtocolCommand::has_dribbler_spin() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RadioProtocolCommand::set_has_dribbler_spin() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RadioProtocolCommand::clear_has_dribbler_spin() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RadioProtocolCommand::clear_dribbler_spin() {
  dribbler_spin_ = 0;
  clear_has_dribbler_spin();
}
inline float RadioProtocolCommand::dribbler_spin() const {
  return dribbler_spin_;
}
inline void RadioProtocolCommand::set_dribbler_spin(float value) {
  set_has_dribbler_spin();
  dribbler_spin_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_radio_5fprotocol_5fcommand_2eproto__INCLUDED
