// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radio_protocol_wrapper.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "radio_protocol_wrapper.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* RadioProtocolWrapper_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RadioProtocolWrapper_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_radio_5fprotocol_5fwrapper_2eproto() {
  protobuf_AddDesc_radio_5fprotocol_5fwrapper_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "radio_protocol_wrapper.proto");
  GOOGLE_CHECK(file != NULL);
  RadioProtocolWrapper_descriptor_ = file->message_type(0);
  static const int RadioProtocolWrapper_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolWrapper, command_),
  };
  RadioProtocolWrapper_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RadioProtocolWrapper_descriptor_,
      RadioProtocolWrapper::default_instance_,
      RadioProtocolWrapper_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolWrapper, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolWrapper, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RadioProtocolWrapper));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_radio_5fprotocol_5fwrapper_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RadioProtocolWrapper_descriptor_, &RadioProtocolWrapper::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_radio_5fprotocol_5fwrapper_2eproto() {
  delete RadioProtocolWrapper::default_instance_;
  delete RadioProtocolWrapper_reflection_;
}

void protobuf_AddDesc_radio_5fprotocol_5fwrapper_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_radio_5fprotocol_5fcommand_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034radio_protocol_wrapper.proto\032\034radio_pr"
    "otocol_command.proto\">\n\024RadioProtocolWra"
    "pper\022&\n\007command\030\001 \003(\0132\025.RadioProtocolCom"
    "mand", 124);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "radio_protocol_wrapper.proto", &protobuf_RegisterTypes);
  RadioProtocolWrapper::default_instance_ = new RadioProtocolWrapper();
  RadioProtocolWrapper::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_radio_5fprotocol_5fwrapper_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_radio_5fprotocol_5fwrapper_2eproto {
  StaticDescriptorInitializer_radio_5fprotocol_5fwrapper_2eproto() {
    protobuf_AddDesc_radio_5fprotocol_5fwrapper_2eproto();
  }
} static_descriptor_initializer_radio_5fprotocol_5fwrapper_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int RadioProtocolWrapper::kCommandFieldNumber;
#endif  // !_MSC_VER

RadioProtocolWrapper::RadioProtocolWrapper()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void RadioProtocolWrapper::InitAsDefaultInstance() {
}

RadioProtocolWrapper::RadioProtocolWrapper(const RadioProtocolWrapper& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void RadioProtocolWrapper::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RadioProtocolWrapper::~RadioProtocolWrapper() {
  SharedDtor();
}

void RadioProtocolWrapper::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RadioProtocolWrapper::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RadioProtocolWrapper::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RadioProtocolWrapper_descriptor_;
}

const RadioProtocolWrapper& RadioProtocolWrapper::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_radio_5fprotocol_5fwrapper_2eproto();
  return *default_instance_;
}

RadioProtocolWrapper* RadioProtocolWrapper::default_instance_ = NULL;

RadioProtocolWrapper* RadioProtocolWrapper::New() const {
  return new RadioProtocolWrapper;
}

void RadioProtocolWrapper::Clear() {
  command_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RadioProtocolWrapper::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .RadioProtocolCommand command = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_command:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_command()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_command;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RadioProtocolWrapper::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .RadioProtocolCommand command = 1;
  for (int i = 0; i < this->command_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->command(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* RadioProtocolWrapper::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .RadioProtocolCommand command = 1;
  for (int i = 0; i < this->command_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->command(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int RadioProtocolWrapper::ByteSize() const {
  int total_size = 0;

  // repeated .RadioProtocolCommand command = 1;
  total_size += 1 * this->command_size();
  for (int i = 0; i < this->command_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->command(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RadioProtocolWrapper::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RadioProtocolWrapper* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RadioProtocolWrapper*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RadioProtocolWrapper::MergeFrom(const RadioProtocolWrapper& from) {
  GOOGLE_CHECK_NE(&from, this);
  command_.MergeFrom(from.command_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RadioProtocolWrapper::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RadioProtocolWrapper::CopyFrom(const RadioProtocolWrapper& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RadioProtocolWrapper::IsInitialized() const {

  for (int i = 0; i < command_size(); i++) {
    if (!this->command(i).IsInitialized()) return false;
  }
  return true;
}

void RadioProtocolWrapper::Swap(RadioProtocolWrapper* other) {
  if (other != this) {
    command_.Swap(&other->command_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RadioProtocolWrapper::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RadioProtocolWrapper_descriptor_;
  metadata.reflection = RadioProtocolWrapper_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
