// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "radio_protocol_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* RadioProtocolCommand_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RadioProtocolCommand_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_radio_5fprotocol_5fcommand_2eproto() {
  protobuf_AddDesc_radio_5fprotocol_5fcommand_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "radio_protocol_command.proto");
  GOOGLE_CHECK(file != NULL);
  RadioProtocolCommand_descriptor_ = file->message_type(0);
  static const int RadioProtocolCommand_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, robot_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, velocity_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, velocity_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, velocity_r_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, flat_kick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, chip_kick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, dribbler_spin_),
  };
  RadioProtocolCommand_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RadioProtocolCommand_descriptor_,
      RadioProtocolCommand::default_instance_,
      RadioProtocolCommand_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioProtocolCommand, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RadioProtocolCommand));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_radio_5fprotocol_5fcommand_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RadioProtocolCommand_descriptor_, &RadioProtocolCommand::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_radio_5fprotocol_5fcommand_2eproto() {
  delete RadioProtocolCommand::default_instance_;
  delete RadioProtocolCommand_reflection_;
}

void protobuf_AddDesc_radio_5fprotocol_5fcommand_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034radio_protocol_command.proto\"\241\001\n\024Radio"
    "ProtocolCommand\022\020\n\010robot_id\030\001 \002(\005\022\022\n\nvel"
    "ocity_x\030\002 \002(\002\022\022\n\nvelocity_y\030\003 \002(\002\022\022\n\nvel"
    "ocity_r\030\004 \002(\002\022\021\n\tflat_kick\030\005 \001(\002\022\021\n\tchip"
    "_kick\030\006 \001(\002\022\025\n\rdribbler_spin\030\007 \001(\002", 194);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "radio_protocol_command.proto", &protobuf_RegisterTypes);
  RadioProtocolCommand::default_instance_ = new RadioProtocolCommand();
  RadioProtocolCommand::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_radio_5fprotocol_5fcommand_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_radio_5fprotocol_5fcommand_2eproto {
  StaticDescriptorInitializer_radio_5fprotocol_5fcommand_2eproto() {
    protobuf_AddDesc_radio_5fprotocol_5fcommand_2eproto();
  }
} static_descriptor_initializer_radio_5fprotocol_5fcommand_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int RadioProtocolCommand::kRobotIdFieldNumber;
const int RadioProtocolCommand::kVelocityXFieldNumber;
const int RadioProtocolCommand::kVelocityYFieldNumber;
const int RadioProtocolCommand::kVelocityRFieldNumber;
const int RadioProtocolCommand::kFlatKickFieldNumber;
const int RadioProtocolCommand::kChipKickFieldNumber;
const int RadioProtocolCommand::kDribblerSpinFieldNumber;
#endif  // !_MSC_VER

RadioProtocolCommand::RadioProtocolCommand()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void RadioProtocolCommand::InitAsDefaultInstance() {
}

RadioProtocolCommand::RadioProtocolCommand(const RadioProtocolCommand& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void RadioProtocolCommand::SharedCtor() {
  _cached_size_ = 0;
  robot_id_ = 0;
  velocity_x_ = 0;
  velocity_y_ = 0;
  velocity_r_ = 0;
  flat_kick_ = 0;
  chip_kick_ = 0;
  dribbler_spin_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RadioProtocolCommand::~RadioProtocolCommand() {
  SharedDtor();
}

void RadioProtocolCommand::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RadioProtocolCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RadioProtocolCommand::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RadioProtocolCommand_descriptor_;
}

const RadioProtocolCommand& RadioProtocolCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_radio_5fprotocol_5fcommand_2eproto();  return *default_instance_;
}

RadioProtocolCommand* RadioProtocolCommand::default_instance_ = NULL;

RadioProtocolCommand* RadioProtocolCommand::New() const {
  return new RadioProtocolCommand;
}

void RadioProtocolCommand::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    robot_id_ = 0;
    velocity_x_ = 0;
    velocity_y_ = 0;
    velocity_r_ = 0;
    flat_kick_ = 0;
    chip_kick_ = 0;
    dribbler_spin_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RadioProtocolCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 robot_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &robot_id_)));
          set_has_robot_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_velocity_x;
        break;
      }
      
      // required float velocity_x = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_velocity_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &velocity_x_)));
          set_has_velocity_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_velocity_y;
        break;
      }
      
      // required float velocity_y = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_velocity_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &velocity_y_)));
          set_has_velocity_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_velocity_r;
        break;
      }
      
      // required float velocity_r = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_velocity_r:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &velocity_r_)));
          set_has_velocity_r();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_flat_kick;
        break;
      }
      
      // optional float flat_kick = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_flat_kick:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &flat_kick_)));
          set_has_flat_kick();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(53)) goto parse_chip_kick;
        break;
      }
      
      // optional float chip_kick = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_chip_kick:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &chip_kick_)));
          set_has_chip_kick();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(61)) goto parse_dribbler_spin;
        break;
      }
      
      // optional float dribbler_spin = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_dribbler_spin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &dribbler_spin_)));
          set_has_dribbler_spin();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RadioProtocolCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 robot_id = 1;
  if (has_robot_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->robot_id(), output);
  }
  
  // required float velocity_x = 2;
  if (has_velocity_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->velocity_x(), output);
  }
  
  // required float velocity_y = 3;
  if (has_velocity_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->velocity_y(), output);
  }
  
  // required float velocity_r = 4;
  if (has_velocity_r()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->velocity_r(), output);
  }
  
  // optional float flat_kick = 5;
  if (has_flat_kick()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->flat_kick(), output);
  }
  
  // optional float chip_kick = 6;
  if (has_chip_kick()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->chip_kick(), output);
  }
  
  // optional float dribbler_spin = 7;
  if (has_dribbler_spin()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->dribbler_spin(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* RadioProtocolCommand::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 robot_id = 1;
  if (has_robot_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->robot_id(), target);
  }
  
  // required float velocity_x = 2;
  if (has_velocity_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->velocity_x(), target);
  }
  
  // required float velocity_y = 3;
  if (has_velocity_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->velocity_y(), target);
  }
  
  // required float velocity_r = 4;
  if (has_velocity_r()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->velocity_r(), target);
  }
  
  // optional float flat_kick = 5;
  if (has_flat_kick()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->flat_kick(), target);
  }
  
  // optional float chip_kick = 6;
  if (has_chip_kick()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->chip_kick(), target);
  }
  
  // optional float dribbler_spin = 7;
  if (has_dribbler_spin()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->dribbler_spin(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int RadioProtocolCommand::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 robot_id = 1;
    if (has_robot_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->robot_id());
    }
    
    // required float velocity_x = 2;
    if (has_velocity_x()) {
      total_size += 1 + 4;
    }
    
    // required float velocity_y = 3;
    if (has_velocity_y()) {
      total_size += 1 + 4;
    }
    
    // required float velocity_r = 4;
    if (has_velocity_r()) {
      total_size += 1 + 4;
    }
    
    // optional float flat_kick = 5;
    if (has_flat_kick()) {
      total_size += 1 + 4;
    }
    
    // optional float chip_kick = 6;
    if (has_chip_kick()) {
      total_size += 1 + 4;
    }
    
    // optional float dribbler_spin = 7;
    if (has_dribbler_spin()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RadioProtocolCommand::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RadioProtocolCommand* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RadioProtocolCommand*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RadioProtocolCommand::MergeFrom(const RadioProtocolCommand& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_robot_id()) {
      set_robot_id(from.robot_id());
    }
    if (from.has_velocity_x()) {
      set_velocity_x(from.velocity_x());
    }
    if (from.has_velocity_y()) {
      set_velocity_y(from.velocity_y());
    }
    if (from.has_velocity_r()) {
      set_velocity_r(from.velocity_r());
    }
    if (from.has_flat_kick()) {
      set_flat_kick(from.flat_kick());
    }
    if (from.has_chip_kick()) {
      set_chip_kick(from.chip_kick());
    }
    if (from.has_dribbler_spin()) {
      set_dribbler_spin(from.dribbler_spin());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RadioProtocolCommand::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RadioProtocolCommand::CopyFrom(const RadioProtocolCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RadioProtocolCommand::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;
  
  return true;
}

void RadioProtocolCommand::Swap(RadioProtocolCommand* other) {
  if (other != this) {
    std::swap(robot_id_, other->robot_id_);
    std::swap(velocity_x_, other->velocity_x_);
    std::swap(velocity_y_, other->velocity_y_);
    std::swap(velocity_r_, other->velocity_r_);
    std::swap(flat_kick_, other->flat_kick_);
    std::swap(chip_kick_, other->chip_kick_);
    std::swap(dribbler_spin_, other->dribbler_spin_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RadioProtocolCommand::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RadioProtocolCommand_descriptor_;
  metadata.reflection = RadioProtocolCommand_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
