// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_status.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "robot_status.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace robot_status {

namespace {

const ::google::protobuf::Descriptor* Fault_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Fault_reflection_ = NULL;
const ::google::protobuf::Descriptor* Fail_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Fail_reflection_ = NULL;
const ::google::protobuf::Descriptor* Robot_Packet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Robot_Packet_reflection_ = NULL;
const ::google::protobuf::Descriptor* Status_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Status_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_robot_5fstatus_2eproto() {
  protobuf_AddDesc_robot_5fstatus_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "robot_status.proto");
  GOOGLE_CHECK(file != NULL);
  Fault_descriptor_ = file->message_type(0);
  static const int Fault_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, shootboard_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, kickfault_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, chipfault_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, encodermotor1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, encodermotor2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, encodermotor3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, encodermotor4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, shootsensor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, beep_),
  };
  Fault_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Fault_descriptor_,
      Fault::default_instance_,
      Fault_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fault, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Fault));
  Fail_descriptor_ = file->message_type(1);
  static const int Fail_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fail, motor1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fail, motor2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fail, motor3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fail, motor4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fail, motor5_),
  };
  Fail_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Fail_descriptor_,
      Fail::default_instance_,
      Fail_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fail, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Fail, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Fail));
  Robot_Packet_descriptor_ = file->message_type(2);
  static const int Robot_Packet_offsets_[12] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, battery_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, spin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, shootsensor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, shootvoltage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, boardid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, fault_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, failed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, halt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, datalost_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, faultmessage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, failedmessage_),
  };
  Robot_Packet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Robot_Packet_descriptor_,
      Robot_Packet::default_instance_,
      Robot_Packet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Robot_Packet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Robot_Packet));
  Status_descriptor_ = file->message_type(3);
  static const int Status_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, robots_),
  };
  Status_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Status_descriptor_,
      Status::default_instance_,
      Status_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Status, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Status));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_robot_5fstatus_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Fault_descriptor_, &Fault::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Fail_descriptor_, &Fail::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Robot_Packet_descriptor_, &Robot_Packet::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Status_descriptor_, &Status::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_robot_5fstatus_2eproto() {
  delete Fault::default_instance_;
  delete Fault_reflection_;
  delete Fail::default_instance_;
  delete Fail_reflection_;
  delete Robot_Packet::default_instance_;
  delete Robot_Packet_reflection_;
  delete Status::default_instance_;
  delete Status_reflection_;
}

void protobuf_AddDesc_robot_5fstatus_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022robot_status.proto\022\014robot_status\"\300\001\n\005F"
    "ault\022\022\n\nshootBoard\030\001 \002(\010\022\021\n\tkickFault\030\002 "
    "\002(\010\022\021\n\tchipFault\030\003 \002(\010\022\025\n\rencoderMotor1\030"
    "\004 \002(\010\022\025\n\rencoderMotor2\030\005 \002(\010\022\025\n\rencoderM"
    "otor3\030\006 \002(\010\022\025\n\rencoderMotor4\030\007 \002(\010\022\023\n\013sh"
    "ootSensor\030\010 \002(\010\022\014\n\004beep\030\t \002(\010\"V\n\004Fail\022\016\n"
    "\006Motor1\030\001 \002(\010\022\016\n\006Motor2\030\002 \002(\010\022\016\n\006Motor3\030"
    "\003 \002(\010\022\016\n\006Motor4\030\004 \002(\010\022\016\n\006Motor5\030\005 \002(\010\"\212\002"
    "\n\014Robot_Packet\022\n\n\002id\030\001 \002(\005\022\017\n\007battery\030\002 "
    "\002(\002\022\014\n\004spin\030\003 \002(\010\022\023\n\013shootsensor\030\004 \002(\010\022\024"
    "\n\014shootVoltage\030\005 \002(\002\022\017\n\007boardID\030\006 \002(\005\022\r\n"
    "\005fault\030\007 \002(\010\022\016\n\006failed\030\010 \002(\010\022\014\n\004halt\030\t \002"
    "(\010\022\020\n\010dataLost\030\n \002(\002\022)\n\014faultMessage\030\013 \001"
    "(\0132\023.robot_status.Fault\022)\n\rfailedMessage"
    "\030\014 \001(\0132\022.robot_status.Fail\"4\n\006Status\022*\n\006"
    "robots\030\001 \003(\0132\032.robot_status.Robot_Packet", 640);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "robot_status.proto", &protobuf_RegisterTypes);
  Fault::default_instance_ = new Fault();
  Fail::default_instance_ = new Fail();
  Robot_Packet::default_instance_ = new Robot_Packet();
  Status::default_instance_ = new Status();
  Fault::default_instance_->InitAsDefaultInstance();
  Fail::default_instance_->InitAsDefaultInstance();
  Robot_Packet::default_instance_->InitAsDefaultInstance();
  Status::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_robot_5fstatus_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_robot_5fstatus_2eproto {
  StaticDescriptorInitializer_robot_5fstatus_2eproto() {
    protobuf_AddDesc_robot_5fstatus_2eproto();
  }
} static_descriptor_initializer_robot_5fstatus_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Fault::kShootBoardFieldNumber;
const int Fault::kKickFaultFieldNumber;
const int Fault::kChipFaultFieldNumber;
const int Fault::kEncoderMotor1FieldNumber;
const int Fault::kEncoderMotor2FieldNumber;
const int Fault::kEncoderMotor3FieldNumber;
const int Fault::kEncoderMotor4FieldNumber;
const int Fault::kShootSensorFieldNumber;
const int Fault::kBeepFieldNumber;
#endif  // !_MSC_VER

Fault::Fault()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Fault::InitAsDefaultInstance() {
}

Fault::Fault(const Fault& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Fault::SharedCtor() {
  _cached_size_ = 0;
  shootboard_ = false;
  kickfault_ = false;
  chipfault_ = false;
  encodermotor1_ = false;
  encodermotor2_ = false;
  encodermotor3_ = false;
  encodermotor4_ = false;
  shootsensor_ = false;
  beep_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Fault::~Fault() {
  SharedDtor();
}

void Fault::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Fault::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Fault::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Fault_descriptor_;
}

const Fault& Fault::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robot_5fstatus_2eproto();
  return *default_instance_;
}

Fault* Fault::default_instance_ = NULL;

Fault* Fault::New() const {
  return new Fault;
}

void Fault::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    shootboard_ = false;
    kickfault_ = false;
    chipfault_ = false;
    encodermotor1_ = false;
    encodermotor2_ = false;
    encodermotor3_ = false;
    encodermotor4_ = false;
    shootsensor_ = false;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    beep_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Fault::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool shootBoard = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &shootboard_)));
          set_has_shootboard();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_kickFault;
        break;
      }

      // required bool kickFault = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_kickFault:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &kickfault_)));
          set_has_kickfault();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_chipFault;
        break;
      }

      // required bool chipFault = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_chipFault:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &chipfault_)));
          set_has_chipfault();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_encoderMotor1;
        break;
      }

      // required bool encoderMotor1 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_encoderMotor1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &encodermotor1_)));
          set_has_encodermotor1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_encoderMotor2;
        break;
      }

      // required bool encoderMotor2 = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_encoderMotor2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &encodermotor2_)));
          set_has_encodermotor2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_encoderMotor3;
        break;
      }

      // required bool encoderMotor3 = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_encoderMotor3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &encodermotor3_)));
          set_has_encodermotor3();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_encoderMotor4;
        break;
      }

      // required bool encoderMotor4 = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_encoderMotor4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &encodermotor4_)));
          set_has_encodermotor4();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_shootSensor;
        break;
      }

      // required bool shootSensor = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_shootSensor:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &shootsensor_)));
          set_has_shootsensor();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_beep;
        break;
      }

      // required bool beep = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_beep:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &beep_)));
          set_has_beep();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Fault::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool shootBoard = 1;
  if (has_shootboard()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->shootboard(), output);
  }

  // required bool kickFault = 2;
  if (has_kickfault()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->kickfault(), output);
  }

  // required bool chipFault = 3;
  if (has_chipfault()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->chipfault(), output);
  }

  // required bool encoderMotor1 = 4;
  if (has_encodermotor1()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->encodermotor1(), output);
  }

  // required bool encoderMotor2 = 5;
  if (has_encodermotor2()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->encodermotor2(), output);
  }

  // required bool encoderMotor3 = 6;
  if (has_encodermotor3()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->encodermotor3(), output);
  }

  // required bool encoderMotor4 = 7;
  if (has_encodermotor4()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->encodermotor4(), output);
  }

  // required bool shootSensor = 8;
  if (has_shootsensor()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->shootsensor(), output);
  }

  // required bool beep = 9;
  if (has_beep()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->beep(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Fault::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool shootBoard = 1;
  if (has_shootboard()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->shootboard(), target);
  }

  // required bool kickFault = 2;
  if (has_kickfault()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->kickfault(), target);
  }

  // required bool chipFault = 3;
  if (has_chipfault()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->chipfault(), target);
  }

  // required bool encoderMotor1 = 4;
  if (has_encodermotor1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->encodermotor1(), target);
  }

  // required bool encoderMotor2 = 5;
  if (has_encodermotor2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->encodermotor2(), target);
  }

  // required bool encoderMotor3 = 6;
  if (has_encodermotor3()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->encodermotor3(), target);
  }

  // required bool encoderMotor4 = 7;
  if (has_encodermotor4()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->encodermotor4(), target);
  }

  // required bool shootSensor = 8;
  if (has_shootsensor()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->shootsensor(), target);
  }

  // required bool beep = 9;
  if (has_beep()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->beep(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Fault::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool shootBoard = 1;
    if (has_shootboard()) {
      total_size += 1 + 1;
    }

    // required bool kickFault = 2;
    if (has_kickfault()) {
      total_size += 1 + 1;
    }

    // required bool chipFault = 3;
    if (has_chipfault()) {
      total_size += 1 + 1;
    }

    // required bool encoderMotor1 = 4;
    if (has_encodermotor1()) {
      total_size += 1 + 1;
    }

    // required bool encoderMotor2 = 5;
    if (has_encodermotor2()) {
      total_size += 1 + 1;
    }

    // required bool encoderMotor3 = 6;
    if (has_encodermotor3()) {
      total_size += 1 + 1;
    }

    // required bool encoderMotor4 = 7;
    if (has_encodermotor4()) {
      total_size += 1 + 1;
    }

    // required bool shootSensor = 8;
    if (has_shootsensor()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required bool beep = 9;
    if (has_beep()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Fault::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Fault* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Fault*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Fault::MergeFrom(const Fault& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_shootboard()) {
      set_shootboard(from.shootboard());
    }
    if (from.has_kickfault()) {
      set_kickfault(from.kickfault());
    }
    if (from.has_chipfault()) {
      set_chipfault(from.chipfault());
    }
    if (from.has_encodermotor1()) {
      set_encodermotor1(from.encodermotor1());
    }
    if (from.has_encodermotor2()) {
      set_encodermotor2(from.encodermotor2());
    }
    if (from.has_encodermotor3()) {
      set_encodermotor3(from.encodermotor3());
    }
    if (from.has_encodermotor4()) {
      set_encodermotor4(from.encodermotor4());
    }
    if (from.has_shootsensor()) {
      set_shootsensor(from.shootsensor());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_beep()) {
      set_beep(from.beep());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Fault::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Fault::CopyFrom(const Fault& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Fault::IsInitialized() const {
  if ((_has_bits_[0] & 0x000001ff) != 0x000001ff) return false;

  return true;
}

void Fault::Swap(Fault* other) {
  if (other != this) {
    std::swap(shootboard_, other->shootboard_);
    std::swap(kickfault_, other->kickfault_);
    std::swap(chipfault_, other->chipfault_);
    std::swap(encodermotor1_, other->encodermotor1_);
    std::swap(encodermotor2_, other->encodermotor2_);
    std::swap(encodermotor3_, other->encodermotor3_);
    std::swap(encodermotor4_, other->encodermotor4_);
    std::swap(shootsensor_, other->shootsensor_);
    std::swap(beep_, other->beep_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Fault::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Fault_descriptor_;
  metadata.reflection = Fault_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Fail::kMotor1FieldNumber;
const int Fail::kMotor2FieldNumber;
const int Fail::kMotor3FieldNumber;
const int Fail::kMotor4FieldNumber;
const int Fail::kMotor5FieldNumber;
#endif  // !_MSC_VER

Fail::Fail()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Fail::InitAsDefaultInstance() {
}

Fail::Fail(const Fail& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Fail::SharedCtor() {
  _cached_size_ = 0;
  motor1_ = false;
  motor2_ = false;
  motor3_ = false;
  motor4_ = false;
  motor5_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Fail::~Fail() {
  SharedDtor();
}

void Fail::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Fail::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Fail::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Fail_descriptor_;
}

const Fail& Fail::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robot_5fstatus_2eproto();
  return *default_instance_;
}

Fail* Fail::default_instance_ = NULL;

Fail* Fail::New() const {
  return new Fail;
}

void Fail::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    motor1_ = false;
    motor2_ = false;
    motor3_ = false;
    motor4_ = false;
    motor5_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Fail::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool Motor1 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &motor1_)));
          set_has_motor1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_Motor2;
        break;
      }

      // required bool Motor2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Motor2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &motor2_)));
          set_has_motor2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_Motor3;
        break;
      }

      // required bool Motor3 = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Motor3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &motor3_)));
          set_has_motor3();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_Motor4;
        break;
      }

      // required bool Motor4 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Motor4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &motor4_)));
          set_has_motor4();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_Motor5;
        break;
      }

      // required bool Motor5 = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_Motor5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &motor5_)));
          set_has_motor5();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Fail::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool Motor1 = 1;
  if (has_motor1()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->motor1(), output);
  }

  // required bool Motor2 = 2;
  if (has_motor2()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->motor2(), output);
  }

  // required bool Motor3 = 3;
  if (has_motor3()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->motor3(), output);
  }

  // required bool Motor4 = 4;
  if (has_motor4()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->motor4(), output);
  }

  // required bool Motor5 = 5;
  if (has_motor5()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->motor5(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Fail::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool Motor1 = 1;
  if (has_motor1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->motor1(), target);
  }

  // required bool Motor2 = 2;
  if (has_motor2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->motor2(), target);
  }

  // required bool Motor3 = 3;
  if (has_motor3()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->motor3(), target);
  }

  // required bool Motor4 = 4;
  if (has_motor4()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->motor4(), target);
  }

  // required bool Motor5 = 5;
  if (has_motor5()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->motor5(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Fail::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool Motor1 = 1;
    if (has_motor1()) {
      total_size += 1 + 1;
    }

    // required bool Motor2 = 2;
    if (has_motor2()) {
      total_size += 1 + 1;
    }

    // required bool Motor3 = 3;
    if (has_motor3()) {
      total_size += 1 + 1;
    }

    // required bool Motor4 = 4;
    if (has_motor4()) {
      total_size += 1 + 1;
    }

    // required bool Motor5 = 5;
    if (has_motor5()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Fail::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Fail* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Fail*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Fail::MergeFrom(const Fail& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_motor1()) {
      set_motor1(from.motor1());
    }
    if (from.has_motor2()) {
      set_motor2(from.motor2());
    }
    if (from.has_motor3()) {
      set_motor3(from.motor3());
    }
    if (from.has_motor4()) {
      set_motor4(from.motor4());
    }
    if (from.has_motor5()) {
      set_motor5(from.motor5());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Fail::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Fail::CopyFrom(const Fail& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Fail::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void Fail::Swap(Fail* other) {
  if (other != this) {
    std::swap(motor1_, other->motor1_);
    std::swap(motor2_, other->motor2_);
    std::swap(motor3_, other->motor3_);
    std::swap(motor4_, other->motor4_);
    std::swap(motor5_, other->motor5_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Fail::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Fail_descriptor_;
  metadata.reflection = Fail_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Robot_Packet::kIdFieldNumber;
const int Robot_Packet::kBatteryFieldNumber;
const int Robot_Packet::kSpinFieldNumber;
const int Robot_Packet::kShootsensorFieldNumber;
const int Robot_Packet::kShootVoltageFieldNumber;
const int Robot_Packet::kBoardIDFieldNumber;
const int Robot_Packet::kFaultFieldNumber;
const int Robot_Packet::kFailedFieldNumber;
const int Robot_Packet::kHaltFieldNumber;
const int Robot_Packet::kDataLostFieldNumber;
const int Robot_Packet::kFaultMessageFieldNumber;
const int Robot_Packet::kFailedMessageFieldNumber;
#endif  // !_MSC_VER

Robot_Packet::Robot_Packet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Robot_Packet::InitAsDefaultInstance() {
  faultmessage_ = const_cast< ::robot_status::Fault*>(&::robot_status::Fault::default_instance());
  failedmessage_ = const_cast< ::robot_status::Fail*>(&::robot_status::Fail::default_instance());
}

Robot_Packet::Robot_Packet(const Robot_Packet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Robot_Packet::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  battery_ = 0;
  spin_ = false;
  shootsensor_ = false;
  shootvoltage_ = 0;
  boardid_ = 0;
  fault_ = false;
  failed_ = false;
  halt_ = false;
  datalost_ = 0;
  faultmessage_ = NULL;
  failedmessage_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Robot_Packet::~Robot_Packet() {
  SharedDtor();
}

void Robot_Packet::SharedDtor() {
  if (this != default_instance_) {
    delete faultmessage_;
    delete failedmessage_;
  }
}

void Robot_Packet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Robot_Packet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Robot_Packet_descriptor_;
}

const Robot_Packet& Robot_Packet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robot_5fstatus_2eproto();
  return *default_instance_;
}

Robot_Packet* Robot_Packet::default_instance_ = NULL;

Robot_Packet* Robot_Packet::New() const {
  return new Robot_Packet;
}

void Robot_Packet::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    battery_ = 0;
    spin_ = false;
    shootsensor_ = false;
    shootvoltage_ = 0;
    boardid_ = 0;
    fault_ = false;
    failed_ = false;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    halt_ = false;
    datalost_ = 0;
    if (has_faultmessage()) {
      if (faultmessage_ != NULL) faultmessage_->::robot_status::Fault::Clear();
    }
    if (has_failedmessage()) {
      if (failedmessage_ != NULL) failedmessage_->::robot_status::Fail::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Robot_Packet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_battery;
        break;
      }

      // required float battery = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_battery:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &battery_)));
          set_has_battery();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_spin;
        break;
      }

      // required bool spin = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_spin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &spin_)));
          set_has_spin();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_shootsensor;
        break;
      }

      // required bool shootsensor = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_shootsensor:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &shootsensor_)));
          set_has_shootsensor();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_shootVoltage;
        break;
      }

      // required float shootVoltage = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_shootVoltage:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &shootvoltage_)));
          set_has_shootvoltage();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_boardID;
        break;
      }

      // required int32 boardID = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_boardID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &boardid_)));
          set_has_boardid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_fault;
        break;
      }

      // required bool fault = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_fault:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &fault_)));
          set_has_fault();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_failed;
        break;
      }

      // required bool failed = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_failed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &failed_)));
          set_has_failed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_halt;
        break;
      }

      // required bool halt = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_halt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &halt_)));
          set_has_halt();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(85)) goto parse_dataLost;
        break;
      }

      // required float dataLost = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_dataLost:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &datalost_)));
          set_has_datalost();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_faultMessage;
        break;
      }

      // optional .robot_status.Fault faultMessage = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_faultMessage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_faultmessage()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(98)) goto parse_failedMessage;
        break;
      }

      // optional .robot_status.Fail failedMessage = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_failedMessage:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_failedmessage()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Robot_Packet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required float battery = 2;
  if (has_battery()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->battery(), output);
  }

  // required bool spin = 3;
  if (has_spin()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->spin(), output);
  }

  // required bool shootsensor = 4;
  if (has_shootsensor()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->shootsensor(), output);
  }

  // required float shootVoltage = 5;
  if (has_shootvoltage()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->shootvoltage(), output);
  }

  // required int32 boardID = 6;
  if (has_boardid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->boardid(), output);
  }

  // required bool fault = 7;
  if (has_fault()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->fault(), output);
  }

  // required bool failed = 8;
  if (has_failed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->failed(), output);
  }

  // required bool halt = 9;
  if (has_halt()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->halt(), output);
  }

  // required float dataLost = 10;
  if (has_datalost()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(10, this->datalost(), output);
  }

  // optional .robot_status.Fault faultMessage = 11;
  if (has_faultmessage()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->faultmessage(), output);
  }

  // optional .robot_status.Fail failedMessage = 12;
  if (has_failedmessage()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->failedmessage(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Robot_Packet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required float battery = 2;
  if (has_battery()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->battery(), target);
  }

  // required bool spin = 3;
  if (has_spin()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->spin(), target);
  }

  // required bool shootsensor = 4;
  if (has_shootsensor()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->shootsensor(), target);
  }

  // required float shootVoltage = 5;
  if (has_shootvoltage()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->shootvoltage(), target);
  }

  // required int32 boardID = 6;
  if (has_boardid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->boardid(), target);
  }

  // required bool fault = 7;
  if (has_fault()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->fault(), target);
  }

  // required bool failed = 8;
  if (has_failed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->failed(), target);
  }

  // required bool halt = 9;
  if (has_halt()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->halt(), target);
  }

  // required float dataLost = 10;
  if (has_datalost()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(10, this->datalost(), target);
  }

  // optional .robot_status.Fault faultMessage = 11;
  if (has_faultmessage()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->faultmessage(), target);
  }

  // optional .robot_status.Fail failedMessage = 12;
  if (has_failedmessage()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        12, this->failedmessage(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Robot_Packet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required float battery = 2;
    if (has_battery()) {
      total_size += 1 + 4;
    }

    // required bool spin = 3;
    if (has_spin()) {
      total_size += 1 + 1;
    }

    // required bool shootsensor = 4;
    if (has_shootsensor()) {
      total_size += 1 + 1;
    }

    // required float shootVoltage = 5;
    if (has_shootvoltage()) {
      total_size += 1 + 4;
    }

    // required int32 boardID = 6;
    if (has_boardid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->boardid());
    }

    // required bool fault = 7;
    if (has_fault()) {
      total_size += 1 + 1;
    }

    // required bool failed = 8;
    if (has_failed()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required bool halt = 9;
    if (has_halt()) {
      total_size += 1 + 1;
    }

    // required float dataLost = 10;
    if (has_datalost()) {
      total_size += 1 + 4;
    }

    // optional .robot_status.Fault faultMessage = 11;
    if (has_faultmessage()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->faultmessage());
    }

    // optional .robot_status.Fail failedMessage = 12;
    if (has_failedmessage()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->failedmessage());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Robot_Packet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Robot_Packet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Robot_Packet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Robot_Packet::MergeFrom(const Robot_Packet& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_battery()) {
      set_battery(from.battery());
    }
    if (from.has_spin()) {
      set_spin(from.spin());
    }
    if (from.has_shootsensor()) {
      set_shootsensor(from.shootsensor());
    }
    if (from.has_shootvoltage()) {
      set_shootvoltage(from.shootvoltage());
    }
    if (from.has_boardid()) {
      set_boardid(from.boardid());
    }
    if (from.has_fault()) {
      set_fault(from.fault());
    }
    if (from.has_failed()) {
      set_failed(from.failed());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_halt()) {
      set_halt(from.halt());
    }
    if (from.has_datalost()) {
      set_datalost(from.datalost());
    }
    if (from.has_faultmessage()) {
      mutable_faultmessage()->::robot_status::Fault::MergeFrom(from.faultmessage());
    }
    if (from.has_failedmessage()) {
      mutable_failedmessage()->::robot_status::Fail::MergeFrom(from.failedmessage());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Robot_Packet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Robot_Packet::CopyFrom(const Robot_Packet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Robot_Packet::IsInitialized() const {
  if ((_has_bits_[0] & 0x000003ff) != 0x000003ff) return false;

  if (has_faultmessage()) {
    if (!this->faultmessage().IsInitialized()) return false;
  }
  if (has_failedmessage()) {
    if (!this->failedmessage().IsInitialized()) return false;
  }
  return true;
}

void Robot_Packet::Swap(Robot_Packet* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(battery_, other->battery_);
    std::swap(spin_, other->spin_);
    std::swap(shootsensor_, other->shootsensor_);
    std::swap(shootvoltage_, other->shootvoltage_);
    std::swap(boardid_, other->boardid_);
    std::swap(fault_, other->fault_);
    std::swap(failed_, other->failed_);
    std::swap(halt_, other->halt_);
    std::swap(datalost_, other->datalost_);
    std::swap(faultmessage_, other->faultmessage_);
    std::swap(failedmessage_, other->failedmessage_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Robot_Packet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Robot_Packet_descriptor_;
  metadata.reflection = Robot_Packet_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Status::kRobotsFieldNumber;
#endif  // !_MSC_VER

Status::Status()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Status::InitAsDefaultInstance() {
}

Status::Status(const Status& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Status::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Status::~Status() {
  SharedDtor();
}

void Status::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Status::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Status::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Status_descriptor_;
}

const Status& Status::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_robot_5fstatus_2eproto();
  return *default_instance_;
}

Status* Status::default_instance_ = NULL;

Status* Status::New() const {
  return new Status;
}

void Status::Clear() {
  robots_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Status::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .robot_status.Robot_Packet robots = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_robots:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_robots()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_robots;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Status::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .robot_status.Robot_Packet robots = 1;
  for (int i = 0; i < this->robots_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->robots(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Status::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .robot_status.Robot_Packet robots = 1;
  for (int i = 0; i < this->robots_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->robots(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Status::ByteSize() const {
  int total_size = 0;

  // repeated .robot_status.Robot_Packet robots = 1;
  total_size += 1 * this->robots_size();
  for (int i = 0; i < this->robots_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->robots(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Status::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Status* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Status*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Status::MergeFrom(const Status& from) {
  GOOGLE_CHECK_NE(&from, this);
  robots_.MergeFrom(from.robots_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Status::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Status::CopyFrom(const Status& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Status::IsInitialized() const {

  for (int i = 0; i < robots_size(); i++) {
    if (!this->robots(i).IsInitialized()) return false;
  }
  return true;
}

void Status::Swap(Status* other) {
  if (other != this) {
    robots_.Swap(&other->robots_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Status::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Status_descriptor_;
  metadata.reflection = Status_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace robot_status

// @@protoc_insertion_point(global_scope)
