// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_status.proto

#ifndef PROTOBUF_robot_5fstatus_2eproto__INCLUDED
#define PROTOBUF_robot_5fstatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace robot_status {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_robot_5fstatus_2eproto();
void protobuf_AssignDesc_robot_5fstatus_2eproto();
void protobuf_ShutdownFile_robot_5fstatus_2eproto();

class Fault;
class Fail;
class Robot_Packet;
class Status;

// ===================================================================

class Fault : public ::google::protobuf::Message {
 public:
  Fault();
  virtual ~Fault();

  Fault(const Fault& from);

  inline Fault& operator=(const Fault& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Fault& default_instance();

  void Swap(Fault* other);

  // implements Message ----------------------------------------------

  Fault* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Fault& from);
  void MergeFrom(const Fault& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool shootBoard = 1;
  inline bool has_shootboard() const;
  inline void clear_shootboard();
  static const int kShootBoardFieldNumber = 1;
  inline bool shootboard() const;
  inline void set_shootboard(bool value);

  // required bool kickFault = 2;
  inline bool has_kickfault() const;
  inline void clear_kickfault();
  static const int kKickFaultFieldNumber = 2;
  inline bool kickfault() const;
  inline void set_kickfault(bool value);

  // required bool chipFault = 3;
  inline bool has_chipfault() const;
  inline void clear_chipfault();
  static const int kChipFaultFieldNumber = 3;
  inline bool chipfault() const;
  inline void set_chipfault(bool value);

  // required bool encoderMotor1 = 4;
  inline bool has_encodermotor1() const;
  inline void clear_encodermotor1();
  static const int kEncoderMotor1FieldNumber = 4;
  inline bool encodermotor1() const;
  inline void set_encodermotor1(bool value);

  // required bool encoderMotor2 = 5;
  inline bool has_encodermotor2() const;
  inline void clear_encodermotor2();
  static const int kEncoderMotor2FieldNumber = 5;
  inline bool encodermotor2() const;
  inline void set_encodermotor2(bool value);

  // required bool encoderMotor3 = 6;
  inline bool has_encodermotor3() const;
  inline void clear_encodermotor3();
  static const int kEncoderMotor3FieldNumber = 6;
  inline bool encodermotor3() const;
  inline void set_encodermotor3(bool value);

  // required bool encoderMotor4 = 7;
  inline bool has_encodermotor4() const;
  inline void clear_encodermotor4();
  static const int kEncoderMotor4FieldNumber = 7;
  inline bool encodermotor4() const;
  inline void set_encodermotor4(bool value);

  // required bool shootSensor = 8;
  inline bool has_shootsensor() const;
  inline void clear_shootsensor();
  static const int kShootSensorFieldNumber = 8;
  inline bool shootsensor() const;
  inline void set_shootsensor(bool value);

  // required bool beep = 9;
  inline bool has_beep() const;
  inline void clear_beep();
  static const int kBeepFieldNumber = 9;
  inline bool beep() const;
  inline void set_beep(bool value);

  // @@protoc_insertion_point(class_scope:robot_status.Fault)
 private:
  inline void set_has_shootboard();
  inline void clear_has_shootboard();
  inline void set_has_kickfault();
  inline void clear_has_kickfault();
  inline void set_has_chipfault();
  inline void clear_has_chipfault();
  inline void set_has_encodermotor1();
  inline void clear_has_encodermotor1();
  inline void set_has_encodermotor2();
  inline void clear_has_encodermotor2();
  inline void set_has_encodermotor3();
  inline void clear_has_encodermotor3();
  inline void set_has_encodermotor4();
  inline void clear_has_encodermotor4();
  inline void set_has_shootsensor();
  inline void clear_has_shootsensor();
  inline void set_has_beep();
  inline void clear_has_beep();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool shootboard_;
  bool kickfault_;
  bool chipfault_;
  bool encodermotor1_;
  bool encodermotor2_;
  bool encodermotor3_;
  bool encodermotor4_;
  bool shootsensor_;
  bool beep_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_robot_5fstatus_2eproto();
  friend void protobuf_AssignDesc_robot_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_robot_5fstatus_2eproto();

  void InitAsDefaultInstance();
  static Fault* default_instance_;
};
// -------------------------------------------------------------------

class Fail : public ::google::protobuf::Message {
 public:
  Fail();
  virtual ~Fail();

  Fail(const Fail& from);

  inline Fail& operator=(const Fail& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Fail& default_instance();

  void Swap(Fail* other);

  // implements Message ----------------------------------------------

  Fail* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Fail& from);
  void MergeFrom(const Fail& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool Motor1 = 1;
  inline bool has_motor1() const;
  inline void clear_motor1();
  static const int kMotor1FieldNumber = 1;
  inline bool motor1() const;
  inline void set_motor1(bool value);

  // required bool Motor2 = 2;
  inline bool has_motor2() const;
  inline void clear_motor2();
  static const int kMotor2FieldNumber = 2;
  inline bool motor2() const;
  inline void set_motor2(bool value);

  // required bool Motor3 = 3;
  inline bool has_motor3() const;
  inline void clear_motor3();
  static const int kMotor3FieldNumber = 3;
  inline bool motor3() const;
  inline void set_motor3(bool value);

  // required bool Motor4 = 4;
  inline bool has_motor4() const;
  inline void clear_motor4();
  static const int kMotor4FieldNumber = 4;
  inline bool motor4() const;
  inline void set_motor4(bool value);

  // required bool Motor5 = 5;
  inline bool has_motor5() const;
  inline void clear_motor5();
  static const int kMotor5FieldNumber = 5;
  inline bool motor5() const;
  inline void set_motor5(bool value);

  // @@protoc_insertion_point(class_scope:robot_status.Fail)
 private:
  inline void set_has_motor1();
  inline void clear_has_motor1();
  inline void set_has_motor2();
  inline void clear_has_motor2();
  inline void set_has_motor3();
  inline void clear_has_motor3();
  inline void set_has_motor4();
  inline void clear_has_motor4();
  inline void set_has_motor5();
  inline void clear_has_motor5();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool motor1_;
  bool motor2_;
  bool motor3_;
  bool motor4_;
  bool motor5_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_robot_5fstatus_2eproto();
  friend void protobuf_AssignDesc_robot_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_robot_5fstatus_2eproto();

  void InitAsDefaultInstance();
  static Fail* default_instance_;
};
// -------------------------------------------------------------------

class Robot_Packet : public ::google::protobuf::Message {
 public:
  Robot_Packet();
  virtual ~Robot_Packet();

  Robot_Packet(const Robot_Packet& from);

  inline Robot_Packet& operator=(const Robot_Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Robot_Packet& default_instance();

  void Swap(Robot_Packet* other);

  // implements Message ----------------------------------------------

  Robot_Packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Robot_Packet& from);
  void MergeFrom(const Robot_Packet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required float battery = 2;
  inline bool has_battery() const;
  inline void clear_battery();
  static const int kBatteryFieldNumber = 2;
  inline float battery() const;
  inline void set_battery(float value);

  // required bool spin = 3;
  inline bool has_spin() const;
  inline void clear_spin();
  static const int kSpinFieldNumber = 3;
  inline bool spin() const;
  inline void set_spin(bool value);

  // required bool shootsensor = 4;
  inline bool has_shootsensor() const;
  inline void clear_shootsensor();
  static const int kShootsensorFieldNumber = 4;
  inline bool shootsensor() const;
  inline void set_shootsensor(bool value);

  // required float shootVoltage = 5;
  inline bool has_shootvoltage() const;
  inline void clear_shootvoltage();
  static const int kShootVoltageFieldNumber = 5;
  inline float shootvoltage() const;
  inline void set_shootvoltage(float value);

  // required int32 boardID = 6;
  inline bool has_boardid() const;
  inline void clear_boardid();
  static const int kBoardIDFieldNumber = 6;
  inline ::google::protobuf::int32 boardid() const;
  inline void set_boardid(::google::protobuf::int32 value);

  // required bool fault = 7;
  inline bool has_fault() const;
  inline void clear_fault();
  static const int kFaultFieldNumber = 7;
  inline bool fault() const;
  inline void set_fault(bool value);

  // required bool failed = 8;
  inline bool has_failed() const;
  inline void clear_failed();
  static const int kFailedFieldNumber = 8;
  inline bool failed() const;
  inline void set_failed(bool value);

  // required bool halt = 9;
  inline bool has_halt() const;
  inline void clear_halt();
  static const int kHaltFieldNumber = 9;
  inline bool halt() const;
  inline void set_halt(bool value);

  // required float dataLost = 10;
  inline bool has_datalost() const;
  inline void clear_datalost();
  static const int kDataLostFieldNumber = 10;
  inline float datalost() const;
  inline void set_datalost(float value);

  // optional .robot_status.Fault faultMessage = 11;
  inline bool has_faultmessage() const;
  inline void clear_faultmessage();
  static const int kFaultMessageFieldNumber = 11;
  inline const ::robot_status::Fault& faultmessage() const;
  inline ::robot_status::Fault* mutable_faultmessage();
  inline ::robot_status::Fault* release_faultmessage();
  inline void set_allocated_faultmessage(::robot_status::Fault* faultmessage);

  // optional .robot_status.Fail failedMessage = 12;
  inline bool has_failedmessage() const;
  inline void clear_failedmessage();
  static const int kFailedMessageFieldNumber = 12;
  inline const ::robot_status::Fail& failedmessage() const;
  inline ::robot_status::Fail* mutable_failedmessage();
  inline ::robot_status::Fail* release_failedmessage();
  inline void set_allocated_failedmessage(::robot_status::Fail* failedmessage);

  // @@protoc_insertion_point(class_scope:robot_status.Robot_Packet)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_battery();
  inline void clear_has_battery();
  inline void set_has_spin();
  inline void clear_has_spin();
  inline void set_has_shootsensor();
  inline void clear_has_shootsensor();
  inline void set_has_shootvoltage();
  inline void clear_has_shootvoltage();
  inline void set_has_boardid();
  inline void clear_has_boardid();
  inline void set_has_fault();
  inline void clear_has_fault();
  inline void set_has_failed();
  inline void clear_has_failed();
  inline void set_has_halt();
  inline void clear_has_halt();
  inline void set_has_datalost();
  inline void clear_has_datalost();
  inline void set_has_faultmessage();
  inline void clear_has_faultmessage();
  inline void set_has_failedmessage();
  inline void clear_has_failedmessage();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  float battery_;
  float shootvoltage_;
  bool spin_;
  bool shootsensor_;
  bool fault_;
  bool failed_;
  ::google::protobuf::int32 boardid_;
  bool halt_;
  ::robot_status::Fault* faultmessage_;
  ::robot_status::Fail* failedmessage_;
  float datalost_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(12 + 31) / 32];

  friend void  protobuf_AddDesc_robot_5fstatus_2eproto();
  friend void protobuf_AssignDesc_robot_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_robot_5fstatus_2eproto();

  void InitAsDefaultInstance();
  static Robot_Packet* default_instance_;
};
// -------------------------------------------------------------------

class Status : public ::google::protobuf::Message {
 public:
  Status();
  virtual ~Status();

  Status(const Status& from);

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Status& default_instance();

  void Swap(Status* other);

  // implements Message ----------------------------------------------

  Status* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .robot_status.Robot_Packet robots = 1;
  inline int robots_size() const;
  inline void clear_robots();
  static const int kRobotsFieldNumber = 1;
  inline const ::robot_status::Robot_Packet& robots(int index) const;
  inline ::robot_status::Robot_Packet* mutable_robots(int index);
  inline ::robot_status::Robot_Packet* add_robots();
  inline const ::google::protobuf::RepeatedPtrField< ::robot_status::Robot_Packet >&
      robots() const;
  inline ::google::protobuf::RepeatedPtrField< ::robot_status::Robot_Packet >*
      mutable_robots();

  // @@protoc_insertion_point(class_scope:robot_status.Status)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::robot_status::Robot_Packet > robots_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_robot_5fstatus_2eproto();
  friend void protobuf_AssignDesc_robot_5fstatus_2eproto();
  friend void protobuf_ShutdownFile_robot_5fstatus_2eproto();

  void InitAsDefaultInstance();
  static Status* default_instance_;
};
// ===================================================================


// ===================================================================

// Fault

// required bool shootBoard = 1;
inline bool Fault::has_shootboard() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Fault::set_has_shootboard() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Fault::clear_has_shootboard() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Fault::clear_shootboard() {
  shootboard_ = false;
  clear_has_shootboard();
}
inline bool Fault::shootboard() const {
  return shootboard_;
}
inline void Fault::set_shootboard(bool value) {
  set_has_shootboard();
  shootboard_ = value;
}

// required bool kickFault = 2;
inline bool Fault::has_kickfault() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Fault::set_has_kickfault() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Fault::clear_has_kickfault() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Fault::clear_kickfault() {
  kickfault_ = false;
  clear_has_kickfault();
}
inline bool Fault::kickfault() const {
  return kickfault_;
}
inline void Fault::set_kickfault(bool value) {
  set_has_kickfault();
  kickfault_ = value;
}

// required bool chipFault = 3;
inline bool Fault::has_chipfault() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Fault::set_has_chipfault() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Fault::clear_has_chipfault() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Fault::clear_chipfault() {
  chipfault_ = false;
  clear_has_chipfault();
}
inline bool Fault::chipfault() const {
  return chipfault_;
}
inline void Fault::set_chipfault(bool value) {
  set_has_chipfault();
  chipfault_ = value;
}

// required bool encoderMotor1 = 4;
inline bool Fault::has_encodermotor1() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Fault::set_has_encodermotor1() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Fault::clear_has_encodermotor1() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Fault::clear_encodermotor1() {
  encodermotor1_ = false;
  clear_has_encodermotor1();
}
inline bool Fault::encodermotor1() const {
  return encodermotor1_;
}
inline void Fault::set_encodermotor1(bool value) {
  set_has_encodermotor1();
  encodermotor1_ = value;
}

// required bool encoderMotor2 = 5;
inline bool Fault::has_encodermotor2() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Fault::set_has_encodermotor2() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Fault::clear_has_encodermotor2() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Fault::clear_encodermotor2() {
  encodermotor2_ = false;
  clear_has_encodermotor2();
}
inline bool Fault::encodermotor2() const {
  return encodermotor2_;
}
inline void Fault::set_encodermotor2(bool value) {
  set_has_encodermotor2();
  encodermotor2_ = value;
}

// required bool encoderMotor3 = 6;
inline bool Fault::has_encodermotor3() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Fault::set_has_encodermotor3() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Fault::clear_has_encodermotor3() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Fault::clear_encodermotor3() {
  encodermotor3_ = false;
  clear_has_encodermotor3();
}
inline bool Fault::encodermotor3() const {
  return encodermotor3_;
}
inline void Fault::set_encodermotor3(bool value) {
  set_has_encodermotor3();
  encodermotor3_ = value;
}

// required bool encoderMotor4 = 7;
inline bool Fault::has_encodermotor4() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Fault::set_has_encodermotor4() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Fault::clear_has_encodermotor4() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Fault::clear_encodermotor4() {
  encodermotor4_ = false;
  clear_has_encodermotor4();
}
inline bool Fault::encodermotor4() const {
  return encodermotor4_;
}
inline void Fault::set_encodermotor4(bool value) {
  set_has_encodermotor4();
  encodermotor4_ = value;
}

// required bool shootSensor = 8;
inline bool Fault::has_shootsensor() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Fault::set_has_shootsensor() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Fault::clear_has_shootsensor() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Fault::clear_shootsensor() {
  shootsensor_ = false;
  clear_has_shootsensor();
}
inline bool Fault::shootsensor() const {
  return shootsensor_;
}
inline void Fault::set_shootsensor(bool value) {
  set_has_shootsensor();
  shootsensor_ = value;
}

// required bool beep = 9;
inline bool Fault::has_beep() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Fault::set_has_beep() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Fault::clear_has_beep() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Fault::clear_beep() {
  beep_ = false;
  clear_has_beep();
}
inline bool Fault::beep() const {
  return beep_;
}
inline void Fault::set_beep(bool value) {
  set_has_beep();
  beep_ = value;
}

// -------------------------------------------------------------------

// Fail

// required bool Motor1 = 1;
inline bool Fail::has_motor1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Fail::set_has_motor1() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Fail::clear_has_motor1() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Fail::clear_motor1() {
  motor1_ = false;
  clear_has_motor1();
}
inline bool Fail::motor1() const {
  return motor1_;
}
inline void Fail::set_motor1(bool value) {
  set_has_motor1();
  motor1_ = value;
}

// required bool Motor2 = 2;
inline bool Fail::has_motor2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Fail::set_has_motor2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Fail::clear_has_motor2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Fail::clear_motor2() {
  motor2_ = false;
  clear_has_motor2();
}
inline bool Fail::motor2() const {
  return motor2_;
}
inline void Fail::set_motor2(bool value) {
  set_has_motor2();
  motor2_ = value;
}

// required bool Motor3 = 3;
inline bool Fail::has_motor3() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Fail::set_has_motor3() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Fail::clear_has_motor3() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Fail::clear_motor3() {
  motor3_ = false;
  clear_has_motor3();
}
inline bool Fail::motor3() const {
  return motor3_;
}
inline void Fail::set_motor3(bool value) {
  set_has_motor3();
  motor3_ = value;
}

// required bool Motor4 = 4;
inline bool Fail::has_motor4() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Fail::set_has_motor4() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Fail::clear_has_motor4() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Fail::clear_motor4() {
  motor4_ = false;
  clear_has_motor4();
}
inline bool Fail::motor4() const {
  return motor4_;
}
inline void Fail::set_motor4(bool value) {
  set_has_motor4();
  motor4_ = value;
}

// required bool Motor5 = 5;
inline bool Fail::has_motor5() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Fail::set_has_motor5() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Fail::clear_has_motor5() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Fail::clear_motor5() {
  motor5_ = false;
  clear_has_motor5();
}
inline bool Fail::motor5() const {
  return motor5_;
}
inline void Fail::set_motor5(bool value) {
  set_has_motor5();
  motor5_ = value;
}

// -------------------------------------------------------------------

// Robot_Packet

// required int32 id = 1;
inline bool Robot_Packet::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Robot_Packet::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Robot_Packet::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Robot_Packet::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Robot_Packet::id() const {
  return id_;
}
inline void Robot_Packet::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required float battery = 2;
inline bool Robot_Packet::has_battery() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Robot_Packet::set_has_battery() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Robot_Packet::clear_has_battery() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Robot_Packet::clear_battery() {
  battery_ = 0;
  clear_has_battery();
}
inline float Robot_Packet::battery() const {
  return battery_;
}
inline void Robot_Packet::set_battery(float value) {
  set_has_battery();
  battery_ = value;
}

// required bool spin = 3;
inline bool Robot_Packet::has_spin() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Robot_Packet::set_has_spin() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Robot_Packet::clear_has_spin() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Robot_Packet::clear_spin() {
  spin_ = false;
  clear_has_spin();
}
inline bool Robot_Packet::spin() const {
  return spin_;
}
inline void Robot_Packet::set_spin(bool value) {
  set_has_spin();
  spin_ = value;
}

// required bool shootsensor = 4;
inline bool Robot_Packet::has_shootsensor() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Robot_Packet::set_has_shootsensor() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Robot_Packet::clear_has_shootsensor() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Robot_Packet::clear_shootsensor() {
  shootsensor_ = false;
  clear_has_shootsensor();
}
inline bool Robot_Packet::shootsensor() const {
  return shootsensor_;
}
inline void Robot_Packet::set_shootsensor(bool value) {
  set_has_shootsensor();
  shootsensor_ = value;
}

// required float shootVoltage = 5;
inline bool Robot_Packet::has_shootvoltage() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Robot_Packet::set_has_shootvoltage() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Robot_Packet::clear_has_shootvoltage() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Robot_Packet::clear_shootvoltage() {
  shootvoltage_ = 0;
  clear_has_shootvoltage();
}
inline float Robot_Packet::shootvoltage() const {
  return shootvoltage_;
}
inline void Robot_Packet::set_shootvoltage(float value) {
  set_has_shootvoltage();
  shootvoltage_ = value;
}

// required int32 boardID = 6;
inline bool Robot_Packet::has_boardid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Robot_Packet::set_has_boardid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Robot_Packet::clear_has_boardid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Robot_Packet::clear_boardid() {
  boardid_ = 0;
  clear_has_boardid();
}
inline ::google::protobuf::int32 Robot_Packet::boardid() const {
  return boardid_;
}
inline void Robot_Packet::set_boardid(::google::protobuf::int32 value) {
  set_has_boardid();
  boardid_ = value;
}

// required bool fault = 7;
inline bool Robot_Packet::has_fault() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Robot_Packet::set_has_fault() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Robot_Packet::clear_has_fault() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Robot_Packet::clear_fault() {
  fault_ = false;
  clear_has_fault();
}
inline bool Robot_Packet::fault() const {
  return fault_;
}
inline void Robot_Packet::set_fault(bool value) {
  set_has_fault();
  fault_ = value;
}

// required bool failed = 8;
inline bool Robot_Packet::has_failed() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Robot_Packet::set_has_failed() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Robot_Packet::clear_has_failed() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Robot_Packet::clear_failed() {
  failed_ = false;
  clear_has_failed();
}
inline bool Robot_Packet::failed() const {
  return failed_;
}
inline void Robot_Packet::set_failed(bool value) {
  set_has_failed();
  failed_ = value;
}

// required bool halt = 9;
inline bool Robot_Packet::has_halt() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Robot_Packet::set_has_halt() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Robot_Packet::clear_has_halt() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Robot_Packet::clear_halt() {
  halt_ = false;
  clear_has_halt();
}
inline bool Robot_Packet::halt() const {
  return halt_;
}
inline void Robot_Packet::set_halt(bool value) {
  set_has_halt();
  halt_ = value;
}

// required float dataLost = 10;
inline bool Robot_Packet::has_datalost() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Robot_Packet::set_has_datalost() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Robot_Packet::clear_has_datalost() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Robot_Packet::clear_datalost() {
  datalost_ = 0;
  clear_has_datalost();
}
inline float Robot_Packet::datalost() const {
  return datalost_;
}
inline void Robot_Packet::set_datalost(float value) {
  set_has_datalost();
  datalost_ = value;
}

// optional .robot_status.Fault faultMessage = 11;
inline bool Robot_Packet::has_faultmessage() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Robot_Packet::set_has_faultmessage() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Robot_Packet::clear_has_faultmessage() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Robot_Packet::clear_faultmessage() {
  if (faultmessage_ != NULL) faultmessage_->::robot_status::Fault::Clear();
  clear_has_faultmessage();
}
inline const ::robot_status::Fault& Robot_Packet::faultmessage() const {
  return faultmessage_ != NULL ? *faultmessage_ : *default_instance_->faultmessage_;
}
inline ::robot_status::Fault* Robot_Packet::mutable_faultmessage() {
  set_has_faultmessage();
  if (faultmessage_ == NULL) faultmessage_ = new ::robot_status::Fault;
  return faultmessage_;
}
inline ::robot_status::Fault* Robot_Packet::release_faultmessage() {
  clear_has_faultmessage();
  ::robot_status::Fault* temp = faultmessage_;
  faultmessage_ = NULL;
  return temp;
}
inline void Robot_Packet::set_allocated_faultmessage(::robot_status::Fault* faultmessage) {
  delete faultmessage_;
  faultmessage_ = faultmessage;
  if (faultmessage) {
    set_has_faultmessage();
  } else {
    clear_has_faultmessage();
  }
}

// optional .robot_status.Fail failedMessage = 12;
inline bool Robot_Packet::has_failedmessage() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Robot_Packet::set_has_failedmessage() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Robot_Packet::clear_has_failedmessage() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Robot_Packet::clear_failedmessage() {
  if (failedmessage_ != NULL) failedmessage_->::robot_status::Fail::Clear();
  clear_has_failedmessage();
}
inline const ::robot_status::Fail& Robot_Packet::failedmessage() const {
  return failedmessage_ != NULL ? *failedmessage_ : *default_instance_->failedmessage_;
}
inline ::robot_status::Fail* Robot_Packet::mutable_failedmessage() {
  set_has_failedmessage();
  if (failedmessage_ == NULL) failedmessage_ = new ::robot_status::Fail;
  return failedmessage_;
}
inline ::robot_status::Fail* Robot_Packet::release_failedmessage() {
  clear_has_failedmessage();
  ::robot_status::Fail* temp = failedmessage_;
  failedmessage_ = NULL;
  return temp;
}
inline void Robot_Packet::set_allocated_failedmessage(::robot_status::Fail* failedmessage) {
  delete failedmessage_;
  failedmessage_ = failedmessage;
  if (failedmessage) {
    set_has_failedmessage();
  } else {
    clear_has_failedmessage();
  }
}

// -------------------------------------------------------------------

// Status

// repeated .robot_status.Robot_Packet robots = 1;
inline int Status::robots_size() const {
  return robots_.size();
}
inline void Status::clear_robots() {
  robots_.Clear();
}
inline const ::robot_status::Robot_Packet& Status::robots(int index) const {
  return robots_.Get(index);
}
inline ::robot_status::Robot_Packet* Status::mutable_robots(int index) {
  return robots_.Mutable(index);
}
inline ::robot_status::Robot_Packet* Status::add_robots() {
  return robots_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::robot_status::Robot_Packet >&
Status::robots() const {
  return robots_;
}
inline ::google::protobuf::RepeatedPtrField< ::robot_status::Robot_Packet >*
Status::mutable_robots() {
  return &robots_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace robot_status

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_robot_5fstatus_2eproto__INCLUDED
